let data = [
    {
        // _id:1,
        name: "Shirt1",
        img: "/images/1.jpg",
        slug: 'shirt1',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "120",
        rating: "5",
        numberofrating: "120",
        instock: "100",
        category: "one",
        cupon:"kire",
        discount: 70,
        discountlimit: 50,
        totalSale: 10
    },
    {
        // _id:2,
        name: "Shirt2",
        img: "/images/2.jpg",
        slug: 'shirt2',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "110",
        rating: "4",
        numberofrating: "140",
        instock: "20",
        category: "one",
        cupon:"tintinatin",
        discount: 50,
        totalSale: 5
    },
    {
        // _id:3,
        name: "Shirt3",
        img: "/images/1.jpg",
        slug: 'shirt3',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "130",
        rating: "3.5",
        numberofrating: "10",
        instock: "0",
        category: "two",
        cupon:"",
        discount:"",
        totalSale: 100
    },
    {
        // _id:4,
        name: "Shirt4",
        img: "/images/2.jpg",
        slug: 'shirt4',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "220",
        rating: "2",
        numberofrating: "120",
        instock: "10",
        category: "two",
        totalSale: 70
    },
    {
        // _id:5,
        name: "Shirt5",
        img: "/images/1.jpg",
        slug: 'shirt5',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "220",
        rating: "5",
        numberofrating: "120",
        instock: "200",
        category: "three",
        totalSale: 50
    },
    {
        // _id:6,
        name: "Shirt6",
        img: "/images/2.jpg",
        slug: 'shirt6',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "220",
        rating: "5",
        numberofrating: "120",
        instock: "200",
        category: "three",
        totalSale: 30
    },
    {
        // _id:7,
        name: "Shirt7",
        img: "/images/1.jpg",
        slug: 'shirt7',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "220",
        rating: "5",
        numberofrating: "120",
        instock: "200",
        category: "four",
        totalSale: 30
    },
    {
        // _id:8,
        name: "Shirt8",
        img: "/images/2.jpg",
        slug: 'shirt8',
        description:"Some quick example text to build on the card title and make up the bulk of the cards content.",
        price: "220",
        rating: "5",
        numberofrating: "120",
        instock: "200",
        category: "four",
        totalSale: 30
    },
]

export default data